Repository QuantWebProject/QuantWeb-SpringServer-, pull requests merged in 2024-08, with the labels that each got.

#30 Setting: 스웨거 설정
  build.gradle
  src/main/java/com/quantweb/springserver/common/config/SwaggerConfig.java
Labels: setting

#42 Hotfix(41) : github action ci 삭제 및 localhost url 변경
  .github/develop.yml
  build.gradle
  src/main/java/com/quantweb/springserver/SpringserverApplication.java
  src/main/java/com/quantweb/springserver/common/entity/BaseTimeEntity.java
  src/main/java/com/quantweb/springserver/common/entity/CustomResponseEntity.java
  src/main/java/com/quantweb/springserver/common/exception/CustomErrorCode.java
  src/main/java/com/quantweb/springserver/common/exception/CustomException.java
  src/main/java/com/quantweb/springserver/common/exception/CustomExceptionHandler.java
  src/main/java/com/quantweb/springserver/domain/auth/config/AuthConfiguration.java
  src/main/java/com/quantweb/springserver/domain/auth/config/AuthInterceptor.java
  src/main/java/com/quantweb/springserver/domain/auth/config/Authenticated.java
  src/main/java/com/quantweb/springserver/domain/auth/config/AuthenticationPrincipal.java
  src/main/java/com/quantweb/springserver/domain/auth/config/AuthenticationRefreshPrincipal.java
  src/main/java/com/quantweb/springserver/domain/auth/config/RefreshTokenAuthInterceptor.java
  src/main/java/com/quantweb/springserver/domain/auth/config/TokenResolver.java
  src/main/java/com/quantweb/springserver/domain/auth/controller/OauthController.java
  src/main/java/com/quantweb/springserver/domain/auth/entity/Token.java
  src/main/java/com/quantweb/springserver/domain/auth/entity/TokenRepository.java
  src/main/java/com/quantweb/springserver/domain/auth/service/OauthService.java
  src/main/java/com/quantweb/springserver/domain/auth/service/TokenService.java
  src/main/java/com/quantweb/springserver/domain/auth/service/dto/response/AccessTokenResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/service/dto/response/LoginResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/service/dto/response/OauthLinkResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/support/CookieExtractor.java
  src/main/java/com/quantweb/springserver/domain/auth/support/JwtTokenProvider.java
  src/main/java/com/quantweb/springserver/domain/auth/support/OAuth2UserInfo.java
  src/main/java/com/quantweb/springserver/domain/auth/support/RandomNickName.java
  src/main/java/com/quantweb/springserver/domain/auth/support/google/GoogleConnector.java
  src/main/java/com/quantweb/springserver/domain/auth/support/google/GoogleProvider.java
  src/main/java/com/quantweb/springserver/domain/auth/support/google/dto/GoogleTokenResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/support/google/dto/GoogleUserResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/support/kakao/KakaoConnector.java
  src/main/java/com/quantweb/springserver/domain/auth/support/kakao/KakaoProvider.java
  src/main/java/com/quantweb/springserver/domain/auth/support/kakao/dto/KakaoTokenResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/support/kakao/dto/KakaoUserResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/support/naver/NaverConnector.java
  src/main/java/com/quantweb/springserver/domain/auth/support/naver/NaverProvider.java
  src/main/java/com/quantweb/springserver/domain/auth/support/naver/dto/NaverTokenResponse.java
  src/main/java/com/quantweb/springserver/domain/auth/support/naver/dto/NaverUserResponse.java
  src/main/java/com/quantweb/springserver/domain/user/controller/UserController.java
  src/main/java/com/quantweb/springserver/domain/user/entity/Oauth.java
  src/main/java/com/quantweb/springserver/domain/user/entity/OauthRepository.java
  src/main/java/com/quantweb/springserver/domain/user/entity/User.java
  src/main/java/com/quantweb/springserver/domain/user/entity/UserRepository.java
  src/main/java/com/quantweb/springserver/domain/user/exception/UserNotExistsException.java
  src/main/java/com/quantweb/springserver/domain/user/service/UserService.java
  src/main/java/com/quantweb/springserver/domain/user/service/dto/response/UserInfoResponse.java
  src/main/java/com/quantweb/springserver/domain/user/user_status/UserStatus.java
  src/main/java/com/quantweb/springserver/domain/user/user_status/UserStatusConverter.java
  src/main/java/com/quantweb/springserver/domain/user_image/entity/UserImage.java
  src/main/java/com/quantweb/springserver/domain/user_image/entity/UserImageRepository.java
  src/main/java/com/quantweb/springserver/domain/user_image/service/UserImageService.java
  src/test/java/com/quantweb/springserver/SpringserverApplicationTests.java
Labels: hotfix

#43 Fix(40): 엔티티 수정
  src/main/java/com/quantweb/springserver/domain/back_test/entity/BackTest.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/DailyPercentage.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/DailyPercentageUs500.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/Graph.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/GraphType.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/Mdd.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/MddUs500.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/entity/InvestmentSectorsPieChart.java
  src/main/java/com/quantweb/springserver/domain/investment_simulation/entity/InvestmentSimulation.java
  src/main/java/com/quantweb/springserver/domain/stock/entity/Stock.java
Labels: setting

#49 Fix(#47): 백테스트 실행하기 수정
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/BackTestInput.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/InvestmentResult.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/StrategySetup.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/TechnicalAnalysisStrategy.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/ValueInvestmentStrategy.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/request/BackTestInput.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/BackTestResultDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/InvestmentResultDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/StrategyInfoDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/controller/BackTestController.java
  src/main/java/com/quantweb/springserver/domain/back_test/converter/BackTestConverter.java
  src/main/java/com/quantweb/springserver/domain/back_test/entity/BackTest.java
  src/main/java/com/quantweb/springserver/domain/back_test/entity/TechnicalStrategy.java
  src/main/java/com/quantweb/springserver/domain/back_test/repository/BackTestRepository.java
  src/main/java/com/quantweb/springserver/domain/back_test/service/BackTestService.java
  src/main/java/com/quantweb/springserver/domain/graph/converter/GraphConverter.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/DailyPercentage.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/DailyPercentageUs500.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/Mdd.java
  src/main/java/com/quantweb/springserver/domain/graph/entity/MddUs500.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/DailyPercentageRepository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/DailyPercentageUs500Repository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/GraphRepository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/MddRepository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/MddUs500Repository.java
  src/main/java/com/quantweb/springserver/domain/graph/service/GraphService.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/converter/PieChartConverter.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/repository/PieChartRepository.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/service/PieChartService.java
  src/main/java/com/quantweb/springserver/domain/investment_simulation/entity/InvestmentSimulation.java
  src/main/java/com/quantweb/springserver/domain/sales_transaction_history/converter/TransactionHistoryConverter.java
  src/main/java/com/quantweb/springserver/domain/sales_transaction_history/entity/SalesTransactionHistory.java
  src/main/java/com/quantweb/springserver/domain/sales_transaction_history/entity/TransactionType.java
  src/main/java/com/quantweb/springserver/domain/sales_transaction_history/repository/TransactionHistoryRepository.java
  src/main/java/com/quantweb/springserver/domain/sales_transaction_history/service/TransactionHistoryService.java
  src/main/java/com/quantweb/springserver/domain/stock/converter/StockConverter.java
  src/main/java/com/quantweb/springserver/domain/stock/repository/StockRepository.java
  src/main/java/com/quantweb/springserver/domain/stock/service/StockService.java
  src/test/java/com/quantweb/springserver/domain/back_test/service/BackTestServiceTest.java
Labels: feature

#34 Feature(#23): 기존 전략 상세 결과 조회
  src/main/java/com/quantweb/springserver/common/config/SshDataSourceConfig.java
  src/main/java/com/quantweb/springserver/common/config/SshTunnelingInitializer.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/request/BackTestRequestDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/BackTestResponseDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/controller/BackTestController.java
  src/main/java/com/quantweb/springserver/domain/back_test/converter/BackTestConverter.java
  src/main/java/com/quantweb/springserver/domain/back_test/entity/BackTest.java
  src/main/java/com/quantweb/springserver/domain/back_test/entity/TechnicalStrategy.java
  src/main/java/com/quantweb/springserver/domain/back_test/service/BackTestService.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/DailyPercentageRepository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/DailyPercentageUs500Repository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/GraphRepository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/MddRepository.java
  src/main/java/com/quantweb/springserver/domain/graph/repository/MddUs500Repository.java
  src/main/java/com/quantweb/springserver/domain/graph/service/GraphService.java
Labels: feature

#51 Feature(35): 투자종목 조회하기
  src/main/java/com/quantweb/springserver/domain/back_test/controller/BackTestController.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/repository/PieChartRepository.java
  src/main/java/com/quantweb/springserver/domain/stock/converter/StockConverter.java
  src/main/java/com/quantweb/springserver/domain/stock/dto/response/StockResponseDto.java
  src/main/java/com/quantweb/springserver/domain/stock/repository/StockRepository.java
  src/main/java/com/quantweb/springserver/domain/stock/service/StockService.java
Labels: feature

#53 Hotfix(52) : cors 오류 해결을 위한 쿠키 헤더 수정
  src/main/java/com/quantweb/springserver/domain/auth/config/AuthConfiguration.java
  src/main/java/com/quantweb/springserver/domain/auth/controller/OauthController.java
  src/main/java/com/quantweb/springserver/domain/auth/service/OauthService.java
  src/main/java/com/quantweb/springserver/domain/back_test/controller/BackTestController.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/repository/PieChartRepository.java
  src/main/java/com/quantweb/springserver/domain/stock/converter/StockConverter.java
  src/main/java/com/quantweb/springserver/domain/stock/dto/response/StockResponseDto.java
  src/main/java/com/quantweb/springserver/domain/stock/repository/StockRepository.java
  src/main/java/com/quantweb/springserver/domain/stock/service/StockService.java
Labels: bug, hotfix

#55 Feature(36) 내 기존 전략 조회
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/BackTestDetailsDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/BackTestResponseDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/BackTestResultDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/controller/BackTestController.java
  src/main/java/com/quantweb/springserver/domain/back_test/converter/BackTestConverter.java
  src/main/java/com/quantweb/springserver/domain/back_test/repository/BackTestRepository.java
  src/main/java/com/quantweb/springserver/domain/back_test/service/BackTestService.java
  src/test/java/com/quantweb/springserver/domain/back_test/service/BackTestServiceTest.java
Labels: feature

#59 Feat(#54): 한투 연동 crud
  src/main/java/com/quantweb/springserver/SpringserverApplication.java
  src/main/java/com/quantweb/springserver/domain/account/controller/AccountController.java
  src/main/java/com/quantweb/springserver/domain/account/dto/request/KoreaInvestmentMockAccountRequest.java
  src/main/java/com/quantweb/springserver/domain/account/dto/response/AccountResponse.java
  src/main/java/com/quantweb/springserver/domain/account/entity/Account.java
  src/main/java/com/quantweb/springserver/domain/account/entity/AccountRepository.java
  src/main/java/com/quantweb/springserver/domain/account/entity/AccountType.java
  src/main/java/com/quantweb/springserver/domain/account/entity/AccountTypeConverter.java
  src/main/java/com/quantweb/springserver/domain/account/service/AccountService.java
  src/main/java/com/quantweb/springserver/domain/auth/controller/OauthController.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/repository/PieChartRepository.java
  src/main/java/com/quantweb/springserver/domain/stock/converter/StockConverter.java
  src/main/java/com/quantweb/springserver/domain/stock/dto/response/StockResponseDto.java
  src/main/java/com/quantweb/springserver/domain/stock/repository/StockRepository.java
  src/main/java/com/quantweb/springserver/domain/stock/service/StockService.java
  src/main/java/com/quantweb/springserver/domain/user_image/entity/UserImage.java
  src/main/java/com/quantweb/springserver/domain/user_image/entity/UserImageRepository.java
  src/main/java/com/quantweb/springserver/domain/user_image/service/UserImageService.java
Labels: feature

#66 Refactor(65): 백테스트 실행하기 인풋 형식 수정
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/request/BackTestInput.java
  src/main/java/com/quantweb/springserver/domain/back_test/converter/BackTestConverter.java
  src/main/java/com/quantweb/springserver/domain/back_test/entity/TechnicalStrategy.java
  src/main/java/com/quantweb/springserver/domain/back_test/service/BackTestService.java
Labels: hotfix

#67 Feature(64): 백테스트 수정/삭제하기
  src/main/java/com/quantweb/springserver/common/exception/ErrorCode.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/request/BackTestRequestDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/response/BackTestResponseDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/controller/BackTestController.java
  src/main/java/com/quantweb/springserver/domain/back_test/converter/BackTestConverter.java
  src/main/java/com/quantweb/springserver/domain/back_test/entity/BackTest.java
  src/main/java/com/quantweb/springserver/domain/back_test/service/BackTestService.java
  src/main/java/com/quantweb/springserver/domain/investment_sectors_pie_chart/service/PieChartService.java
  src/main/java/com/quantweb/springserver/domain/sales_transaction_history/service/TransactionHistoryService.java
  src/main/java/com/quantweb/springserver/domain/stock/service/StockService.java
Labels: feature, hotfix

#68 Refactor: 요청 형식 수정
  src/main/java/com/quantweb/springserver/domain/back_test/DTO/request/BackTestRequestDto.java
  src/main/java/com/quantweb/springserver/domain/back_test/converter/BackTestConverter.java
Labels: hotfix
